export const exports = [
	'lib/index.ts',

	'lib/array.ts',
	'lib/async.ts',
	'lib/counter.ts',
	'lib/dom.ts',
	'lib/error.ts',
	'lib/function.ts',
	'lib/id.ts',
	'lib/json.ts',
	'lib/log.ts',
	'lib/map.ts',
	'lib/maths.ts',
	'lib/object.ts',
	'lib/obtainable.ts',
	'lib/path.ts',
	'lib/path-parsing.ts',
	'lib/print.ts',
	'lib/process.ts',
	'lib/random.ts',
	'lib/random-alea.ts',
	'lib/result.ts',
	'lib/regexp.ts',
	'lib/string.ts',
	'lib/timings.ts',
	'lib/types.ts',
];
