// generated by src/lib/exportsData.gen.ts

export interface ExportsData {
	path: string;
	identifiers: string[];
}

export const exportsData: ExportsData[] = [
	{path: 'lib/array.ts', identifiers: ['EMPTY_ARRAY', 'removeUnordered', 'toArray', 'toNext']},
	{path: 'lib/async.ts', identifiers: ['wait']},
	{path: 'lib/counter.ts', identifiers: ['toCounter']},
	{path: 'lib/env.ts', identifiers: ['env', 'toEnvNumber', 'toEnvString']},
	{path: 'lib/function.ts', identifiers: ['identity', 'lazy', 'noop']},
	{path: 'lib/id.ts', identifiers: ['isUuid', 'toToClientId', 'uuidMatcher']},
	{path: 'lib/json.ts', identifiers: ['getJsonType']},
	{
		path: 'lib/log.ts',
		identifiers: [
			'BaseLogger',
			'DEFAULT_LOG_LEVEL',
			'ENV_LOG_LEVEL',
			'LogLevel',
			'Logger',
			'SystemLogger',
			'configureLogLevel',
			'printLogLabel',
		],
	},
	{path: 'lib/map.ts', identifiers: ['compareSimpleMapEntries', 'sortMap']},
	{
		path: 'lib/maths.ts',
		identifiers: [
			'GR',
			'GR2',
			'GR2i',
			'GR3',
			'GR3i',
			'GR4',
			'GR4i',
			'GR5',
			'GR5i',
			'GR6',
			'GR6i',
			'GR7',
			'GR7i',
			'GR8',
			'GR8i',
			'GR9',
			'GR9i',
			'GRi',
			'clamp',
			'lerp',
			'round',
		],
	},
	{
		path: 'lib/object.ts',
		identifiers: [
			'EMPTY_OBJECT',
			'mapRecord',
			'nulls',
			'omit',
			'omitUndefined',
			'pickBy',
			'reorder',
			'traverse',
			'undefineds',
		],
	},
	{path: 'lib/obtainable.ts', identifiers: ['toObtainable']},
	{
		path: 'lib/path.ts',
		identifiers: ['replaceExtension', 'stripTrailingSlash', 'toCommonBaseDir', 'toPathStem'],
	},
	{path: 'lib/path-parsing.ts', identifiers: ['toPathParts', 'toPathPieces', 'toPathSegments']},
	{path: 'lib/random.ts', identifiers: ['randomBool', 'randomFloat', 'randomInt', 'randomItem']},
	{path: 'lib/random-alea.ts', identifiers: ['toMash', 'toRandomAlea']},
	{
		path: 'lib/string.ts',
		identifiers: [
			'deindent',
			'ensureEnd',
			'ensureStart',
			'plural',
			'stripAfter',
			'stripBefore',
			'stripEnd',
			'stripStart',
			'toGraphemeCount',
			'truncate',
		],
	},
	{path: 'lib/timings.ts', identifiers: ['Timings', 'createStopwatch']},
];

// generated by src/lib/exportsData.gen.ts
