import type {Gen} from '@feltjs/gro';
import {toRootPath} from '@feltjs/gro/dist/paths.js';

import {exports} from '$lib/exports';

// TODO put this on `exports` as data somehow, probably
const excludedExportsFromRoot = new Set(['lib/path.ts', 'lib/process.ts']);

export const gen: Gen = ({originId, log}) => {
	return `
    // generated by /${toRootPath(originId)}

    ${exports
			.map((file) => {
				console.log(`file`, file);
				for (const excluded of excludedExportsFromRoot) {
					if (file === excluded) {
						return `// excluding ${file}`;
					}
				}
				if (file.endsWith('.ts')) {
					if (file.endsWith('index.ts')) return '';
					return `export * from '.${file.slice(3, -3)}';`;
				} else {
					log.warn('unknown file', file);
					return '';
				}
			})
			.join('\n')}

    // generated by /${toRootPath(originId)}
  `;
};
