import type {Gen} from '@feltjs/gro';
import {toRootPath} from '@feltjs/gro/dist/paths.js';

import {exports} from '$lib/exports';

export const gen: Gen = ({originId, log}) => {
	return `
    // generated by /${toRootPath(originId)}

    ${exports
			.map((file) => {
				if (file.endsWith('.ts')) {
					if (file.endsWith('index.ts')) return '';
					return `export * from '$${file.slice(0, -3)}';`;
				} else {
					log.warn('unknown file', file);
					return '';
				}
			})
			.join('\n')}

    // generated by /${toRootPath(originId)}
  `;
};
