import type {PackageJson} from '@grogarden/gro/package_json.js';

export const package_json = {
	name: '@grogarden/util',
	description: 'JS utilities to complement the modern web platform 🦕🐋',
	version: '0.15.2',
	license: 'MIT',
	homepage: 'https://util.grogarden.org/',
	author: {name: 'Felt Co-op', email: 'team@felt.social', url: 'https://www.felt.social/'},
	repository: {type: 'git', url: 'git+https://github.com/grogarden/util.git'},
	bugs: {url: 'https://github.com/grogarden/util/issues', email: 'team@felt.social'},
	type: 'module',
	engines: {node: '>=20.7'},
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		test: 'gro test',
		deploy: 'gro deploy',
	},
	keywords: ['js', 'typescript', 'utilities', 'web'],
	files: ['dist'],
	peerDependencies: {kleur: '^4.0.0'},
	devDependencies: {
		'@changesets/changelog-git': '^0.1.14',
		'@feltjs/eslint-config': '^0.4.0',
		'@fuz.dev/fuz': '^0.73.0',
		'@fuz.dev/fuz_library': '^0.11.0',
		'@grogarden/gro': '^0.95.8',
		'@sveltejs/adapter-static': '^2.0.3',
		'@sveltejs/kit': '^1.26.0',
		'@sveltejs/package': '^2.2.2',
		'@types/node': '^20.8.7',
		'@typescript-eslint/eslint-plugin': '^6.8.0',
		'@typescript-eslint/parser': '^6.8.0',
		eslint: '^8.51.0',
		'eslint-plugin-svelte': '^2.34.0',
		kleur: '^4.1.5',
		prettier: '^3.0.3',
		'prettier-plugin-svelte': '^3.0.3',
		svelte: '^4.2.2',
		'svelte-check': '^3.5.2',
		tslib: '^2.6.2',
		typescript: '^5.2.2',
		uvu: '^0.5.6',
	},
	eslintConfig: {root: true, extends: '@feltjs'},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	exports: {
		'./array.js': {default: './dist/array.js', types: './dist/array.d.ts'},
		'./async.js': {default: './dist/async.js', types: './dist/async.d.ts'},
		'./counter.js': {default: './dist/counter.js', types: './dist/counter.d.ts'},
		'./dom.js': {default: './dist/dom.js', types: './dist/dom.d.ts'},
		'./error.js': {default: './dist/error.js', types: './dist/error.d.ts'},
		'./function.js': {default: './dist/function.js', types: './dist/function.d.ts'},
		'./id.js': {default: './dist/id.js', types: './dist/id.d.ts'},
		'./json.js': {default: './dist/json.js', types: './dist/json.d.ts'},
		'./log.js': {default: './dist/log.js', types: './dist/log.d.ts'},
		'./map.js': {default: './dist/map.js', types: './dist/map.d.ts'},
		'./maths.js': {default: './dist/maths.js', types: './dist/maths.d.ts'},
		'./object.js': {default: './dist/object.js', types: './dist/object.d.ts'},
		'./obtainable.js': {default: './dist/obtainable.js', types: './dist/obtainable.d.ts'},
		'./package.gen.js': {default: './dist/package.gen.js', types: './dist/package.gen.d.ts'},
		'./package.js': {default: './dist/package.js', types: './dist/package.d.ts'},
		'./path.js': {default: './dist/path.js', types: './dist/path.d.ts'},
		'./print.js': {default: './dist/print.js', types: './dist/print.d.ts'},
		'./process.js': {default: './dist/process.js', types: './dist/process.d.ts'},
		'./random_alea.js': {default: './dist/random_alea.js', types: './dist/random_alea.d.ts'},
		'./random.js': {default: './dist/random.js', types: './dist/random.d.ts'},
		'./regexp.js': {default: './dist/regexp.js', types: './dist/regexp.d.ts'},
		'./result.js': {default: './dist/result.js', types: './dist/result.d.ts'},
		'./string.js': {default: './dist/string.js', types: './dist/string.d.ts'},
		'./timings.js': {default: './dist/timings.js', types: './dist/timings.d.ts'},
		'./types.js': {default: './dist/types.js', types: './dist/types.d.ts'},
	},
} satisfies PackageJson;
